/**
 * Codex-style collapsed thinking display.
 *
 * While a thinking run streams, the transcript shows a tool-row-style header
 * plus the current tail line of the reasoning:
 *
 *   • Thinking 4s
 *     └ The user wants me to change the thinking display, so first I need…
 *
 * Once the run closes (the model moved on to text or tool calls, or the
 * message finished), it collapses to the duration header plus a one-line
 * summary of the reasoning:
 *
 *   • Thought for 12s
 *     └ I patched AssistantMessageComponent to render collapsed thinking rows.
 *
 * The rows reuse pi-ui's tool-row look (dot + bold verb, `└` continuation in
 * the thinking color), so thinking reads like any other tool activity.
 *
 * The summary sentence is generated by the model itself: a nested
 * `completeSimple` call condenses the run into one sentence. Until it lands
 * (typically 1–2s), the run's last line — usually the model's own conclusion
 * — stands in as the interim summary and is replaced in place. Short runs
 * (≤2 lines) skip the call; failures keep the interim line. Like
 * pi-smart-flow's compact-thinking, summaries are TUI-only: the assistant
 * message and its thinking signatures are never modified.
 *
 * Timing, identity, and Pi's streaming protocol: `message_update` events
 * carry a fresh `{ ...partial }` shallow copy on EVERY delta (pi-agent-core
 * agent-loop.js), so per-object WeakMap tracking alone would reset each
 * delta. Durations are therefore accumulated in module-level live arrays
 * keyed by run index, and committed into a WeakMap on the final message
 * object at `message_end` — the object later chat rebuilds reuse.
 *
 * ctrl+t toggles between this collapsed pair and Pi's full italic thinking
 * markdown. Because both states of Pi's old "Hide thinking" setting are now
 * superseded (collapsed summary / expanded full text), the settings entry is
 * removed from the settings list.
 *
 * Mechanics, following tools.ts conventions:
 *   - `AssistantMessageComponent.prototype.updateContent` is re-implemented
 *     for messages that contain thinking and delegated to the original for
 *     everything else (so text blocks keep Pi's exact markdown pipeline).
 *     Any unexpected shape falls back to the original renderer.
 *   - `InteractiveMode.prototype.toggleThinkingBlockVisibility` (the ctrl+t
 *     action) is wrapped to flip this module's expansion flag; the original
 *     still performs the chat rebuild and streaming-component refresh.
 *   - `SettingsList.prototype.render` drops the "hide-thinking" item.
 *   - `pi.on("message_update")` keeps the freshest ExtensionContext (model +
 *     API key) for summary calls; the editor factory hand-off captures the
 *     TUI so a landed summary can request an immediate re-render.
 */

import type { ExtensionAPI, ExtensionContext, MarkdownTransformContext, MarkdownTransformer, Theme } from "@earendil-works/pi-coding-agent";
import { AssistantMessageComponent, InteractiveMode } from "@earendil-works/pi-coding-agent";
import { completeSimple } from "@earendil-works/pi-ai/compat";
import type { MarkdownTheme } from "@earendil-works/pi-tui";
import { SettingsList, Spacer, Text, Markdown, truncateToWidth, visibleWidth } from "@earendil-works/pi-tui";
import type { Component, TUI } from "@earendil-works/pi-tui";
import { fgRgb } from "./gradient.ts";
import { DOT_DONE, DOT_RUNNING } from "./tools.ts";

/** Theme captured at the latest session_start; fallback for resolveTheme(). */
let activeTheme: Theme | undefined;
/** Module-level expansion state; false = collapsed Codex-style rows. */
let thinkingExpanded = false;
/** Guard so pi.on context hooks are registered exactly once per process. */
let eventsRegistered = false;

/** Shared global theme instance Pi publishes for cross-loader access. */
const PI_THEME_KEY = Symbol.for("@earendil-works/pi-coding-agent:theme");

/**
 * Resolve the current theme lazily: the shared global instance is live and
 * already initialized when restored sessions render their chat *before*
 * session_start delivers ctx.ui.theme (see InteractiveMode.run()).
 */
function resolveTheme(): Theme | undefined {
  const shared = (globalThis as typeof globalThis & { [PI_THEME_KEY]?: Theme })[PI_THEME_KEY];
  return shared ?? activeTheme;
}

const ASSISTANT_ORIGINAL = Symbol.for("@NekoSekaiMoe/pi-ui:assistant-message-update-content");
const MODE_TOGGLE_ORIGINAL = Symbol.for("@NekoSekaiMoe/pi-ui:thinking-toggle-original");
const SETTINGS_LIST_ORIGINAL = Symbol.for("@NekoSekaiMoe/pi-ui:settings-list-render");
const HIDE_THINKING_ID = "hide-thinking";

/** Stable subset of AssistantMessage content blocks used here. */
interface ContentBlockLike {
  type: string;
  text?: string;
  thinking?: string;
}

interface AssistantMessageLike {
  content: ContentBlockLike[];
  stopReason?: string;
  errorMessage?: string;
}

/** Stable subset of the AssistantMessageComponent internals this patch drives. */
interface AssistantMessageState {
  contentContainer: { clear(): void; addChild(child: unknown): void };
  markdownTheme: MarkdownTheme;
  markdownTransformers?: MarkdownTransformer[];
  outputPad: number;
  isStreaming: boolean;
  lastMessage: AssistantMessageLike | undefined;
  hasToolCalls: boolean;
  invalidate?(): void;
}

interface InteractiveModeState {
  showStatus?: (message: string) => void;
}

interface SettingsListState {
  items?: { id?: string }[];
  filteredItems?: { id?: string }[];
}

/** One maximal run of consecutive non-empty thinking blocks. */
interface ThinkingRun {
  startIndex: number;
  endIndex: number;
  joined: string;
  /** True once text or tool-call content follows the run in the message. */
  closed: boolean;
}

/**
 * Timing/summary state for the message currently streaming. Partial message
 * copies get a new identity every delta, so live state is module-level and
 * indexed by run position instead.
 */
interface LiveRunTiming {
  startedAt: number;
  lastGrowAt: number;
  lastLength: number;
  closedAt?: number;
}

let liveRuns: LiveRunTiming[] = [];
let liveSummaries: (string | undefined)[] = [];
let livePending: boolean[] = [];
/** Last partial-copy object rendered in live mode; also receives the commit. */
let lastPartialMessage: object | undefined;
/** Component that last rendered live updates; only it may commit the live state
 *  at message_end — rebuilt components render other messages with streaming=false. */
let lastLiveComponent: AssistantMessageState | undefined;

/** Committed per-run state for a finalized message object (survives rebuilds). */
interface FinalRunState {
  durations: (number | undefined)[];
  summaries: (string | undefined)[];
  pending: boolean[];
}

const finalRuns = new WeakMap<object, FinalRunState>();

/** Freshest ExtensionContext (model + modelRegistry + signal), from events. */
let latestCtx: ExtensionContext | undefined;
/** TUI captured from the editor factory; used to repaint when a summary lands. */
let requestRender: (() => void) | undefined;
/** Components showing interim summaries; invalidated when a summary lands. */
const summaryWaiters = new Set<{ invalidate?(): void }>();

const SUMMARY_PROMPT =
  "You condense an AI assistant's private reasoning trace into a single line. " +
  "Summarize the reasoning below in ONE concise sentence, in the same language as the input: " +
  "what was being worked out and the conclusion or next action. " +
  "Output only that sentence — no preamble, no quotes, no bullet markers.";
/** Runs at or below this many non-empty lines skip the LLM call entirely. */
const MIN_LLM_SUMMARY_LINES = 3;
/** Keep summarization input bounded; conclusions live near the end, so keep the tail. */
const MAX_SUMMARY_INPUT_CHARS = 12_000;
const SUMMARY_HEAD_CHARS = 2_000;
const SUMMARY_MAX_TOKENS = 256;

/** Test seam: replaced by the smoke test to avoid real API calls. */
export type RunSummarizer = (thinking: string) => Promise<string | undefined>;
let runSummarizer: RunSummarizer = defaultRunSummarizer;

/** @internal Test seam for injecting a fake summarizer. */
export function __overrideRunSummarizer(fn: RunSummarizer): void {
  runSummarizer = fn;
}

const ANSI_PATTERN = /\x1b\[[0-?]*[ -/]*[@-~]/g;

function isVisibleBlock(block: ContentBlockLike): boolean {
  if (block.type === "text") return (block.text ?? "").trim().length > 0;
  if (block.type === "thinking") return (block.thinking ?? "").trim().length > 0;
  return false;
}

function hasThinkingContent(message: AssistantMessageLike): boolean {
  return message.content.some((block) => block.type === "thinking" && (block.thinking ?? "").trim().length > 0);
}

function nonEmptyLineCount(text: string): number {
  return text.split("\n").filter((line) => line.trim().length > 0).length;
}

/** Mirrors Pi's createMarkdownTransform: apply registered markdown transformers. */
function composeTransform(
  messageType: MarkdownTransformContext["messageType"],
  isStreaming: boolean,
  transformers: MarkdownTransformer[] | undefined,
): ((markdown: string, availableWidth: number) => string) | undefined {
  if (!transformers || transformers.length === 0) return undefined;
  return (markdown: string, availableWidth: number): string => {
    let output = markdown;
    for (const transformer of transformers) {
      try {
        const transformed = transformer(output, { messageType, isStreaming, availableWidth });
        if (typeof transformed === "string") output = transformed;
      } catch {
        // Keep the current markdown and continue with the next transformer.
      }
    }
    return output;
  };
}

function lastNonEmptyLine(text: string): string {
  const lines = text.split("\n");
  for (let i = lines.length - 1; i >= 0; i--) {
    const trimmed = lines[i]!.trim();
    if (trimmed) return trimmed;
  }
  return "";
}

function formatDuration(milliseconds: number): string {
  const totalSeconds = Math.max(0, Math.round(milliseconds / 1000));
  if (totalSeconds < 1) return "<1s";
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return minutes > 0 ? `${minutes}m ${seconds}s` : `${seconds}s`;
}

function boundSummaryInput(text: string): string {
  if (text.length <= MAX_SUMMARY_INPUT_CHARS) return text;
  return `${text.slice(0, SUMMARY_HEAD_CHARS)}\n[...]\n${text.slice(-(MAX_SUMMARY_INPUT_CHARS - SUMMARY_HEAD_CHARS))}`;
}

/** Default summarizer: one nested `completeSimple` call against the live model. */
async function defaultRunSummarizer(thinking: string): Promise<string | undefined> {
  const ctx = latestCtx;
  const model = ctx?.model;
  if (!ctx || !model) return undefined;
  try {
    const apiKey = await ctx.modelRegistry.getApiKeyForProvider(model.provider);
    const response = await completeSimple(
      model,
      {
        systemPrompt: SUMMARY_PROMPT,
        messages: [{ role: "user", content: boundSummaryInput(thinking), timestamp: Date.now() }],
      },
      // "off" is not a valid SimpleStreamOptions.reasoning value; "minimal"
      // keeps the summarization call itself from burning reasoning tokens.
      { apiKey, signal: ctx.signal, maxTokens: SUMMARY_MAX_TOKENS, reasoning: "minimal" },
    );
    if (ctx.signal?.aborted) return undefined;
    const text = response.content
      .filter((block) => block.type === "text")
      .map((block) => (block as { text: string }).text)
      .join(" ")
      .replace(/\s+/g, " ")
      .trim();
    if (response.stopReason === "error" || response.stopReason === "aborted" || !text) return undefined;
    return text;
  } catch {
    // Keep the interim last line on any summarization failure.
    return undefined;
  }
}

/** Cache a landed summary and repaint every waiting collapsed row. */
function completeRunSummary(message: object, runIndex: number, summary: string | undefined): void {
  if (summary) {
    const state = finalRuns.get(message);
    if (state) state.summaries[runIndex] = summary;
    else liveSummaries[runIndex] = summary;
  }
  // Snapshot first: invalidate() re-registers still-pending components into
  // the set, and iterating a live Set would revisit (and re-invalidate) them.
  const current = [...summaryWaiters];
  summaryWaiters.clear();
  for (const waiter of current) {
    try {
      waiter.invalidate?.();
    } catch {
      // A discarded component; nothing to repaint.
    }
  }
  try {
    requestRender?.();
  } catch {
    // The next natural render pass picks the summary up.
  }
}

/** Start (once) or read the pending/landed LLM summary for a closed run. */
function resolveClosedSummary(
  message: object,
  runIndex: number,
  run: ThinkingRun,
  live: boolean,
  component: unknown,
): string {
  const interim = lastNonEmptyLine(run.joined);
  const start = () => {
    summaryWaiters.add(component as { invalidate?(): void });
    void runSummarizer(run.joined)
      .then((summary) => completeRunSummary(message, runIndex, summary))
      .catch(() => completeRunSummary(message, runIndex, undefined));
  };

  if (live) {
    if (liveSummaries[runIndex]) return liveSummaries[runIndex]!;
    if (livePending[runIndex]) {
      summaryWaiters.add(component as { invalidate?(): void });
      return interim;
    }
    if (nonEmptyLineCount(run.joined) < MIN_LLM_SUMMARY_LINES) return interim;
    livePending[runIndex] = true;
    start();
    return interim;
  }

  const state = finalRuns.get(message);
  if (!state) return interim; // restored from disk / never observed live
  if (state.summaries[runIndex]) return state.summaries[runIndex]!;
  if (state.pending[runIndex]) {
    summaryWaiters.add(component as { invalidate?(): void });
    return interim;
  }
  if (nonEmptyLineCount(run.joined) < MIN_LLM_SUMMARY_LINES) return interim;
  state.pending[runIndex] = true;
  start();
  return interim;
}

/**
 * Two-row thinking block in pi-ui's tool-row style: dot + bold verb header
 * (`• Thinking 4s` / `• Thought for 12s`) and a `└` continuation line in the
 * thinking color, truncated to the render width. Flush-left like tool rows.
 */
class ThinkingRow implements Component {
  private live: boolean;
  private elapsedMs?: number;
  private durationMs?: number;
  private line: string;
  private cachedWidth = -1;
  private cachedLines: string[] = [];

  constructor(options: { live: boolean; elapsedMs?: number; durationMs?: number; line: string }) {
    this.live = options.live;
    this.elapsedMs = options.elapsedMs;
    this.durationMs = options.durationMs;
    this.line = options.line;
  }

  invalidate(): void {
    this.cachedWidth = -1;
    this.cachedLines = [];
  }

  render(width: number): string[] {
    const theme = resolveTheme();
    if (!theme || width <= 0) return [];
    if (this.cachedWidth === width) return this.cachedLines;

    const dot = fgRgb("•", this.live ? DOT_RUNNING : DOT_DONE);
    const verb = theme.bold(theme.fg("toolTitle", this.live ? "Thinking" : "Thought"));
    let meta = "";
    if (this.live && this.elapsedMs !== undefined) {
      meta = " " + theme.fg("dim", formatDuration(this.elapsedMs));
    } else if (!this.live && this.durationMs !== undefined) {
      meta = theme.fg("dim", " for ") + theme.fg("dim", formatDuration(this.durationMs));
    }
    const header = `${dot} ${verb}${meta}`;

    // truncateToWidth emits reset sequences around the ellipsis; strip them so
    // the branch line keeps one consistent thinkingText style.
    const branch = theme.fg("dim", "  └ ");
    const body = theme.italic(
      theme.fg("thinkingText", truncateToWidth(this.line, Math.max(1, width - visibleWidth(branch)), "…").replace(ANSI_PATTERN, "")),
    );

    const padToWidth = (line: string): string => line + " ".repeat(Math.max(0, width - visibleWidth(line)));
    this.cachedWidth = width;
    this.cachedLines = [padToWidth(header), padToWidth(branch + body)];
    return this.cachedLines;
  }
}

/** Collect maximal consecutive thinking runs, skipping all-empty runs (as Pi does). */
function collectThinkingRuns(message: AssistantMessageLike): ThinkingRun[] {
  const runs: ThinkingRun[] = [];
  const content = message.content;
  for (let i = 0; i < content.length; i++) {
    if (content[i]!.type !== "thinking") continue;
    const blocks: string[] = [];
    const startIndex = i;
    while (i < content.length && content[i]!.type === "thinking") {
      const thinking = (content[i]!.thinking ?? "").trim();
      if (thinking) blocks.push(thinking);
      i++;
    }
    const endIndex = i - 1;
    if (blocks.length === 0) continue;
    const closed = content
      .slice(endIndex + 1)
      .some((block) => block.type === "toolCall" || (block.type === "text" && (block.text ?? "").trim().length > 0));
    runs.push({ startIndex, endIndex, joined: blocks.join("\n\n"), closed });
  }
  return runs;
}

/** Accumulate live timings for the streaming message's runs (identity-proof). */
function syncLiveTimings(runs: ThinkingRun[]): void {
  const now = Date.now();
  for (let i = 0; i < runs.length; i++) {
    const run = runs[i]!;
    let timing = liveRuns[i];
    if (!timing) timing = liveRuns[i] = { startedAt: now, lastGrowAt: now, lastLength: run.joined.length };
    if (run.joined.length > timing.lastLength) {
      timing.lastGrowAt = now;
      timing.lastLength = run.joined.length;
    }
    if (run.closed && timing.closedAt === undefined) timing.closedAt = timing.lastGrowAt;
  }
  if (liveRuns.length > runs.length) liveRuns.length = runs.length;
}

/**
 * Commit live timings/summaries onto the finalized message object (the exact
 * object chat rebuilds reuse). Only the component that streamed the message
 * may commit — chat rebuilds of older messages also render with
 * streaming=false and must never steal the live state. Run count is a cheap
 * sanity check; joined lengths are NOT compared because the finalized message
 * may normalize whitespace without changing which runs were timed.
 */
function commitLiveState(component: AssistantMessageState, message: object, runs: ThinkingRun[]): FinalRunState | undefined {
  if (liveRuns.length === 0 || component !== lastLiveComponent) return undefined;
  if (runs.length !== liveRuns.length) return undefined;
  const state: FinalRunState = {
    durations: liveRuns.map((t) => (t.closedAt !== undefined ? t.closedAt - t.startedAt : t.lastGrowAt - t.startedAt)),
    summaries: [...liveSummaries],
    pending: [...livePending],
  };
  finalRuns.set(message, state);
  // The streaming component may still hold the last partial copy; late
  // invalidations of it must find the committed state too.
  if (lastPartialMessage && lastPartialMessage !== message) finalRuns.set(lastPartialMessage, state);
  liveRuns = [];
  liveSummaries = [];
  livePending = [];
  lastPartialMessage = undefined;
  lastLiveComponent = undefined;
  return state;
}

/**
 * Re-implementation of AssistantMessageComponent.updateContent with Codex-style
 * thinking rows. Text blocks, spacing, and stop-reason/error rows mirror the
 * original renderer; only thinking runs change presentation.
 */
function renderCodexThinking(state: AssistantMessageState, message: AssistantMessageLike, streaming: boolean): void {
  const theme = resolveTheme()!;
  state.lastMessage = message;
  state.isStreaming = streaming;
  state.contentContainer.clear();

  if (message.content.some(isVisibleBlock)) {
    state.contentContainer.addChild(new Spacer(1));
  }

  const runs = collectThinkingRuns(message);
  if (streaming) {
    lastPartialMessage = message;
    lastLiveComponent = state;
    syncLiveTimings(runs);
  }
  const committed = streaming ? undefined : commitLiveState(state, message, runs) ?? finalRuns.get(message);
  const content = message.content;

  let runCursor = 0;
  for (let i = 0; i < content.length; i++) {
    const block = content[i]!;
    if (block.type === "text" && (block.text ?? "").trim()) {
      state.contentContainer.addChild(
        new Markdown(block.text!.trim(), state.outputPad, 0, state.markdownTheme, undefined, {
          transform: composeTransform("assistant", streaming, state.markdownTransformers),
        }),
      );
      continue;
    }
    if (block.type !== "thinking") continue;

    const run = runs[runCursor];
    if (run && run.startIndex === i) {
      const runIndex = runCursor;
      runCursor++;
      i = run.endIndex;

      const hasVisibleContentAfter = content.slice(i + 1).some(isVisibleBlock);
      if (thinkingExpanded) {
        // Expanded: Pi's full italic thinking markdown, transforms included.
        state.contentContainer.addChild(
          new Markdown(run.joined, state.outputPad, 0, state.markdownTheme, {
            color: (text: string) => theme.fg("thinkingText", text),
            italic: true,
          }, {
            transform: composeTransform("assistant-thinking", streaming, state.markdownTransformers),
          }),
        );
      } else if (streaming && !run.closed) {
        // Live tail: gray dot + ticking duration, single most recent line.
        const timing = liveRuns[runIndex];
        state.contentContainer.addChild(
          new ThinkingRow({
            live: true,
            elapsedMs: timing ? Date.now() - timing.startedAt : undefined,
            line: lastNonEmptyLine(run.joined),
          }),
        );
      } else {
        // Done: green dot + duration header plus the one-line summary. The
        // model condenses the run (async); its last line stands in until then.
        let durationMs: number | undefined;
        if (streaming) {
          const timing = liveRuns[runIndex];
          if (timing?.closedAt !== undefined) durationMs = timing.closedAt - timing.startedAt;
        } else {
          durationMs = committed?.durations[runIndex];
        }
        const summary = resolveClosedSummary(message, runIndex, run, streaming, state);
        state.contentContainer.addChild(
          new ThinkingRow({
            live: false,
            durationMs,
            line: summary,
          }),
        );
      }
      if (hasVisibleContentAfter) {
        state.contentContainer.addChild(new Spacer(1));
      }
    } else {
      // An all-empty thinking run: consume it silently, exactly like Pi.
      while (i < content.length && content[i]!.type === "thinking") i++;
      i--;
    }
  }

  // Mirror Pi's stop-reason/error rows (render() reads hasToolCalls for OSC).
  const hasToolCalls = content.some((c) => c.type === "toolCall");
  state.hasToolCalls = hasToolCalls;
  if (message.stopReason === "length") {
    state.contentContainer.addChild(new Spacer(1));
    state.contentContainer.addChild(
      new Text(theme.fg("error", "Response was truncated before completion."), state.outputPad, 0),
    );
  } else if (!hasToolCalls) {
    if (message.stopReason === "aborted") {
      const abortMessage =
        message.errorMessage && message.errorMessage !== "Request was aborted" ? message.errorMessage : "Operation aborted";
      state.contentContainer.addChild(new Spacer(1));
      state.contentContainer.addChild(new Text(theme.fg("error", abortMessage), state.outputPad, 0));
    } else if (message.stopReason === "error") {
      const errorMsg = message.errorMessage || "Unknown error";
      state.contentContainer.addChild(new Spacer(1));
      state.contentContainer.addChild(new Text(theme.fg("error", `Error: ${errorMsg}`), state.outputPad, 0));
    }
  }
}

/** Install the Codex thinking renderer on AssistantMessageComponent. */
function installAssistantMessagePatch(): void {
  const prototype = AssistantMessageComponent.prototype as unknown as Record<PropertyKey, unknown>;
  if (typeof prototype.updateContent !== "function" || prototype[ASSISTANT_ORIGINAL]) return;
  const originalUpdateContent = prototype.updateContent as (
    this: AssistantMessageState,
    message?: AssistantMessageLike,
    isStreaming?: boolean,
  ) => void;
  prototype[ASSISTANT_ORIGINAL] = originalUpdateContent;

  prototype.updateContent = function (this: AssistantMessageState, message?: AssistantMessageLike, isStreaming?: boolean) {
    const streaming = isStreaming ?? this.isStreaming;
    // message_start renders a thinking-less partial: the reliable per-message
    // reset point for the live timing/summary arrays (partial copies have no
    // stable identity across deltas).
    if (streaming && message && !hasThinkingContent(message)) {
      liveRuns = [];
      liveSummaries = [];
      livePending = [];
      lastPartialMessage = undefined;
      lastLiveComponent = undefined;
    }
    if (!message || !hasThinkingContent(message) || !resolveTheme()) {
      originalUpdateContent.call(this, message, streaming);
      return;
    }
    try {
      renderCodexThinking(this, message, streaming);
    } catch {
      // Unexpected message/component shape: keep Pi's default rendering.
      originalUpdateContent.call(this, message, streaming);
    }
  };
}

/**
 * ctrl+t reinterpreted: flip this module's expansion flag, then reuse Pi's
 * original toggle (chat rebuild + streaming-component refresh + persistence)
 * so every rendered message immediately reflects the new state.
 */
function installThinkingTogglePatch(): void {
  const prototype = InteractiveMode.prototype as unknown as Record<PropertyKey, unknown>;
  const original = prototype.toggleThinkingBlockVisibility;
  if (typeof original !== "function" || prototype[MODE_TOGGLE_ORIGINAL]) return;
  prototype[MODE_TOGGLE_ORIGINAL] = original;

  prototype.toggleThinkingBlockVisibility = function (this: InteractiveModeState) {
    thinkingExpanded = !thinkingExpanded;
    (original as (this: InteractiveModeState) => void).call(this);
    try {
      this.showStatus?.(
        thinkingExpanded ? "Thinking expanded · ctrl+t to collapse" : "Thinking collapsed · ctrl+t to expand",
      );
    } catch {
      // The status line is cosmetic.
    }
  };
}

/** Drop the "hide-thinking" entry from every rendered settings list. */
function installSettingsFilterPatch(): void {
  const prototype = SettingsList.prototype as unknown as Record<PropertyKey, unknown>;
  const original = prototype.render;
  if (typeof original !== "function" || prototype[SETTINGS_LIST_ORIGINAL]) return;
  prototype[SETTINGS_LIST_ORIGINAL] = original;

  prototype.render = function (this: SettingsListState, width: number): string[] {
    try {
      if (Array.isArray(this.items) && this.items.some((item) => item?.id === HIDE_THINKING_ID)) {
        this.items = this.items.filter((item) => item?.id !== HIDE_THINKING_ID);
        this.filteredItems = this.items;
      }
    } catch {
      // Keep the original list on any unexpected shape.
    }
    return (original as (this: SettingsListState, width: number) => string[]).call(this, width);
  };
}

/**
 * Activate the Codex thinking display. Prototype patches are process-lifetime
 * and idempotent (see tools.ts for the rationale); `pi` event hooks for the
 * summary model context are registered once. The theme is refreshed on every
 * TUI session_start so theme switches are followed via the live proxy.
 */
export function installThinkingDisplay(pi?: ExtensionAPI, theme?: Theme): void {
  if (theme) activeTheme = theme;
  installAssistantMessagePatch();
  installThinkingTogglePatch();
  installSettingsFilterPatch();
  if (pi && !eventsRegistered) {
    eventsRegistered = true;
    // Keep the freshest model context for summary generation. message_update
    // fires throughout streaming, so latestCtx.model tracks model switches.
    pi.on("message_update", (_event, ctx) => {
      latestCtx = ctx;
    });
    pi.on("message_end", (_event, ctx) => {
      latestCtx = ctx;
    });
  }
}

/**
 * Capture the TUI (from the editor factory in index.ts) so landed summaries
 * can request an immediate repaint instead of waiting for the next render.
 */
export function captureRenderTrigger(tui: TUI): void {
  requestRender = () => tui.requestRender();
}
